name: Meta Generator

on:
  push:
    paths:
      - '*.js'
  pull_request:
    paths:
      - '*.js'
  workflow_dispatch:

jobs:
  Generate Meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show files
        run: ls | echo
      
#     - name: Commit changes
#       run: git commit -m "Generated Meta" -a
